#!/bin/bash
############################################################################
# This is a script to create the runs necessary for Project Silent Night   #
# This one script will cover both SMEFT and WEFT both in KD and dispersion #
# Classification Level: For Her Majesty's eyes ONLY.                       #
# -- Ayan Paul (December 2018, Berlin)                                     #
############################################################################

EXEPATH=/home/apaul/beegfs/HEPfit/Analysis/dist/Release_MPI/Intel-Linux/analysis
## BATCH is SLURM or CONDOR
BATCH="SLURM"

## BSM
## First lets make the ones in both KD and dispersion
## Directory Structure:
## -- WEFT                    --SMEFT                    --SM
##    |-- KD   --dispersion     |-- KD   --dispersion      |-- KD   --dispersion

# rm -rf WEFT SMEFT
mkdir -p  SMEFT SM

# SM
cd SM
for hads in KD dispersion
do
    mkdir -p ${hads} && cd ${hads}
    for run in SM
    do
	mkdir -p ${run} && cd ${run}
	cp -r ../../../config .
	sed -i.bak -e "s/## StandardModel/StandardModel/" config/StandardModel.conf
	rm config/*NPSMEFTd6.conf
	rm config/*WEFT.conf
	if [ ${hads} == 'KD' ]; then
	    rm config/dispersion.conf
	    sed -i.bak -e "s/USEDISP/false/" -e "s/## KD ## //" config/StandardModel.conf
	elif [ ${hads} == 'dispersion' ]; then
	    rm config/*h_lambda.conf 
	    sed -i.bak -e "s/USEDISP/true/" -e "s/## DISP ## //" config/StandardModel.conf
	fi
	rm -rf analysis *.txt *.out *.err analysis Observables *.pdf *.tex config/*.bak
	ln -s ${EXEPATH} .
        #./analysis config/StandardModel.conf --noMC
	if [ ${BATCH} == 'SLURM' ]; then
	    sed -e "s/NAME/${run}-${hads}/" ../../../sbatch.sh > sbatch.sh
	    sbatch sbatch.sh
	elif [ ${BATCH} == 'CONDOR' ]; then
	    sed -e "/FAME/s/NAME/${run}-${hads}/" ../../../submit_condor.sh > submit_condor.sh
	    cp ../../../mpi-wrap.sh .
	    condor_submit submit_condor.sh
	fi
	cd ..
    done
    cd ..
done
cd ..

# Then SMEFT
cd SMEFT
for hads in KD dispersion
do
    mkdir -p ${hads} && cd ${hads}
    for run in CLQ1_2223 C_all_22 CLQ1_2223_CQe_2322
    do
	mkdir -p ${run} && cd ${run}
	cp -r ../../../config .
	sed -i.bak -e "s/## NPD6 ## //" config/StandardModel.conf
	rm config/*WEFT.conf
	if [ ${hads} == 'KD' ]; then
	    rm config/dispersion.conf
	    sed -i.bak -e "s/USEDISP/false/" -e "s/## KD ## //" config/StandardModel.conf
	elif [ ${hads} == 'dispersion' ]; then
	    rm config/*h_lambda.conf 
	    sed -i.bak -e "s/USEDISP/true/" -e "s/## DISP ## //" config/StandardModel.conf
	fi
	case ${run} in
	    CLQ1_2223)
		sed -i.bak -e "/CLQ1_2223/s/RANGE_2/2./" -e "s/RANGE_1/0./;s/RANGE_2/0./" config/NPSMEFTd6.conf
		sed -i.bak -e "/CLQ1_2223/s/^# //" config/Observables_NP_NPSMEFTd6.conf
		;;
	    C_all_22)
		sed -i.bak -e "/CLQ1_2223/s/RANGE_2/5./;/CLd_2223/s/RANGE_2/2./;/CLd_2223/s/0./-0.5/" -e "s/RANGE_2/5./" -e "s/RANGE_1/0./" config/NPSMEFTd6.conf
		sed -i.bak -e "/22/s/^# //" config/Observables_NP_NPSMEFTd6.conf
		;;
	    CLQ1_2223_CQe_2322)
		sed -i.bak -e "/CLQ1_2223/s/RANGE_2/2./;/CQe_2322/s/RANGE_2/2.5/" -e "s/RANGE_1/0./;s/RANGE_2/0./" config/NPSMEFTd6.conf
		sed -i.bak -e "/CLQ1_2223/s/^# //;/CQe_2322/s/^# //" config/Observables_NP_NPSMEFTd6.conf
		;;
	esac
	rm -rf analysis *.txt *.out *.err analysis Observables *.pdf *.tex config/*.bak
	ln -s ${EXEPATH} .
        #./analysis config/StandardModel.conf --noMC
	if [ ${BATCH} == 'SLURM' ]; then
	    sed -e "s/NAME/${run}-${hads}/" ../../../sbatch.sh > sbatch.sh
	    sbatch sbatch.sh
	elif [ ${BATCH} == 'CONDOR' ]; then
	    sed -e "/FAME/s/NAME/${run}-${hads}/" ../../../submit_condor.sh > submit_condor.sh
	    cp ../../../mpi-wrap.sh .
	    condor_submit submit_condor.sh
	fi
	cd ..
    done
    cd ..
done
cd ..


